// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5MDwKJYZmIa5V-gdArJlh4LeAa3EtgUA',
    appId: '1:166895019053:web:3d728e7898092d328dc4a4',
    messagingSenderId: '166895019053',
    projectId: 'crisant-develop',
    authDomain: 'crisant-develop.firebaseapp.com',
    storageBucket: 'crisant-develop.firebasestorage.app',
    measurementId: 'G-0FDJ4PFEXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYYyYmpH3njNea5hFDdV6wSZnkNrgWKuk',
    appId: '1:166895019053:android:8a23d1ac7b31de518dc4a4',
    messagingSenderId: '166895019053',
    projectId: 'crisant-develop',
    storageBucket: 'crisant-develop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNDSNUenll9gAL-0bHEvEJZtYJsYi31mc',
    appId: '1:166895019053:ios:8ad504dd216e42838dc4a4',
    messagingSenderId: '166895019053',
    projectId: 'crisant-develop',
    storageBucket: 'crisant-develop.firebasestorage.app',
    iosBundleId: 'com.example.crisentPannel',
  );
}
